# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/motorola/cancunf-motcamera/setup-makefiles.sh


# SamSung_Camera App
PRODUCT_PACKAGES += \
    WingCam-N28 \
    privapp_whitelist_com.sec.android.app.camera.xml

# Libs
PRODUCT_COPY_FILES += \
    vendor/samsung/wing-camera/proprietary/system/lib64/libBSD_jni.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libBSD_jni.so \
    vendor/samsung/wing-camera/proprietary/system/lib64/libBST_DualCalibration_Service.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libBST_DualCalibration_Service.so \
	vendor/samsung/wing-camera/proprietary/system/lib64/libBSTAiScene.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libBSTAiScene.so \
	vendor/samsung/wing-camera/proprietary/system/lib64/libBSTbase_share.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libBSTbase_share.so \
	vendor/samsung/wing-camera/proprietary/system/lib64/libBSTBeauty.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libBSTBeauty.so \	
	vendor/samsung/wing-camera/proprietary/system/lib64/libBSTDocShadowRemove.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libBSTDocShadowRemove.so \	
	vendor/samsung/wing-camera/proprietary/system/lib64/libBSTFaceDetction.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libBSTFaceDetction.so \	
	vendor/samsung/wing-camera/proprietary/system/lib64/libBSTFoodMode.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libBSTFoodMode.so \	
	vendor/samsung/wing-camera/proprietary/system/lib64/libBSTHDRDETECT.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libBSTHDRDETECT.so \	
	vendor/samsung/wing-camera/proprietary/system/lib64/libBSTHdrDynamicJni.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libBSTHdrDynamicJni.so \	
	vendor/samsung/wing-camera/proprietary/system/lib64/libBSTMultiExpoGainHDR.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libBSTMultiExpoGainHDR.so \	
	vendor/samsung/wing-camera/proprietary/system/lib64/libBSTSingleAIDoc.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libBSTSingleAIDoc.so \	
	vendor/samsung/wing-camera/proprietary/system/lib64/libBSTSpecialEffect.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libBSTSpecialEffect.so \	
	vendor/samsung/wing-camera/proprietary/system/lib64/libBstStick2D.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libBstStick2D.so \	
	vendor/samsung/wing-camera/proprietary/system/lib64/libc++_shared.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libc++_shared.so \	
	vendor/samsung/wing-camera/proprietary/system/lib64/libdualAfternative-lib.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libdualAfternative-lib.so \	
	vendor/samsung/wing-camera/proprietary/system/lib64/libdualAfterSale.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libdualAfterSale.so \	
	vendor/samsung/wing-camera/proprietary/system/lib64/libfusion.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libfusion.so \	
	vendor/samsung/wing-camera/proprietary/system/lib64/libjni_imageutils.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libjni_imageutils.so \	
	vendor/samsung/wing-camera/proprietary/system/lib64/libjniBstAiDoc.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libjniBstAiDoc.so \	
	vendor/samsung/wing-camera/proprietary/system/lib64/libjniBstAiScene.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libjniBstAiScene.so \	
	vendor/samsung/wing-camera/proprietary/system/lib64/libjniBstBeauty.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libjniBstBeauty.so \	
	vendor/samsung/wing-camera/proprietary/system/lib64/libjniBstFoodMode.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libjniBstFoodMode.so \	
	vendor/samsung/wing-camera/proprietary/system/lib64/libjniBstSticker.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libjniBstSticker.so \	
	vendor/samsung/wing-camera/proprietary/system/lib64/libmt_detect_palm.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libmt_detect_palm.so \	
	vendor/samsung/wing-camera/proprietary/system/lib64/libmt_filter_gl.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libmt_filter_gl.so \	
	vendor/samsung/wing-camera/proprietary/system/lib64/libmt_portrait_matting.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libmt_portrait_matting.so \	
	vendor/samsung/wing-camera/proprietary/system/lib64/libMTFilters.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libMTFilters.so \	
	vendor/samsung/wing-camera/proprietary/system/lib64/libMTFiltersPreview.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libMTFiltersPreview.so \	
	vendor/samsung/wing-camera/proprietary/system/lib64/libMTRefocus_jni.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libMTRefocus_jni.so \	
	vendor/samsung/wing-camera/proprietary/system/lib64/libMTRefocus.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libMTRefocus.so \	
	vendor/samsung/wing-camera/proprietary/system/lib64/libMTSingleBokeh_jni.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libMTSingleBokeh_jni.so \	
	vendor/samsung/wing-camera/proprietary/system/lib64/libMTSingleBokeh.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libMTSingleBokeh.so \	
	vendor/samsung/wing-camera/proprietary/system/lib64/libSEF.quram.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libSEF.quram.so \	
	vendor/samsung/wing-camera/proprietary/system/lib64/libwingrefocusJni.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libwingrefocusJni.so \	
	vendor/samsung/wing-camera/proprietary/system/lib64/libwt_blur.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libwt_blur.so \	
	vendor/samsung/wing-camera/proprietary/system/lib64/libwt_panorama.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libwt_panorama.so 
	vendor/samsung/wing-camera/proprietary/system/lib64/libjpega.camera.samsung.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libjpega.camera.samsung.so 
	vendor/samsung/wing-camera/proprietary/system/lib64/libimagecodec.quram.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libimagecodec.quram.so 
	vendor/samsung/wing-camera/proprietary/system/lib64/libfloatingfeature.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libfloatingfeature.so 
	vendor/samsung/wing-camera/proprietary/system/lib64/libagifencoder.quram.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libagifencoder.quram.so 
	vendor/samsung/wing-camera/proprietary/system/lib64/libBarcodeReader.quram.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libBarcodeReader.quram.so 
	vendor/samsung/wing-camera/proprietary/system/lib64/libexifa.camera.samsung.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libexifa.camera.samsung.so 
	vendor/samsung/wing-camera/proprietary/system/etc/floating_feature.so:$(TARGET_COPY_OUT_SYSTEM)/etc/floating_feature.so 


#Spoof
PRODUCT_SYSTEM_PROPERTIES += \
	ro.jdm_dev.manufacturer=samsung \
	ro.jdm_dev.model=SM-A055F \
	ro.jdm_dev.name=a05mxx \
	ro.jdm_dev.device=a05m \
	ro.csc.country_code=Sri Lanka \
	ro.csc.countryiso_code=SLK

PRODUCT_SOONG_NAMESPACES += \
    vendor/samsung/wing-camera
